{% set name = "SISPPEO" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/inrae/{{ name }}/archive/v{{ version }}-cnes.tar.gz
  sha256: a62e4f315083ee460bbb37d473b6afeae38144789e4b47c9c546a37b9cc80b96

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - sisppeo = sisppeo.cli:cli

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - affine
    - click
    - colorcet
    - datashader
    - fiona
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pillow
    - plotly
    - psutil
    - pvlib-python
    - pyproj
    - pyyaml
    - rasterio
    - ray-core
    - s2cloudless
    - scikit-image
    - scikit-learn
    - scipy
    - shapely
    - tqdm
    - xarray

test:
  imports:
    - sisppeo

about:
  home: https://github.com/inrae/SISPPEO
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Satellite Imagery & Signal Processing Packages for Earth Observation'
  description: |
    SISPPEO is an open source project and Python package (with a CLI)
    allowing one to extract synthetic information useful for Earth observation
    (Water and Land) from satellite optical imagery (e.g, Sentinel-2/MSI,
    Sentinel-3/OLCI, Landsat 8/OLI…).
  dev_url: https://gitlab.irstea.fr/telquel-obs2co/satellite/sisppeo/-/tree/dev
  doc_url: https://inrae.github.io/SISPPEO

extra:
  recipe-maintainers:
    - acoque
